"""add last_read_seq

Revision ID: 06adf9d21486
Revises: 2445c42ed980
Create Date: 2026-03-15 06:25:38.603210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06adf9d21486'
down_revision: Union[str, Sequence[str], None] = '2445c42ed980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_members', sa.Column('last_read_seq', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_members', 'last_read_seq')
    # ### end Alembic commands ###
