"""add message seq

Revision ID: 2445c42ed980
Revises: b5e669a69402
Create Date: 2026-03-14 06:40:28.642629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2445c42ed980'
down_revision: Union[str, Sequence[str], None] = 'b5e669a69402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('seq', sa.Integer(), nullable=False))
    op.create_index('ix_messages_chat_seq', 'messages', ['chat_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_chat_seq', table_name='messages')
    op.drop_column('messages', 'seq')
    # ### end Alembic commands ###
