"""add delivered seq

Revision ID: a46935f61045
Revises: 06adf9d21486
Create Date: 2026-03-17 06:49:35.361962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46935f61045'
down_revision: Union[str, Sequence[str], None] = '06adf9d21486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_members', sa.Column('last_delivered_seq', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'chat_members', ['user_id', 'chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_members', type_='unique')
    op.drop_column('chat_members', 'last_delivered_seq')
    # ### end Alembic commands ###
