"""create chats

Revision ID: b5e669a69402
Revises: 96665eeef26b
Create Date: 2026-03-12 14:33:09.228774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5e669a69402'
down_revision: Union[str, Sequence[str], None] = '96665eeef26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_members', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chat_members', 'chat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('chats', sa.Column('title', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('chats', 'is_group',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('messages', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.drop_column('messages', 'sender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('messages', 'user_id')
    op.alter_column('chats', 'is_group',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('chats', 'created_at')
    op.drop_column('chats', 'title')
    op.alter_column('chat_members', 'chat_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chat_members', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
